import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/providers/theme-provider";
import { Onest } from "next/font/google";
import localFont from "next/font/local";
import { Viewport, Metadata } from "next";
import { ToasterComponent } from "@/providers/toaster";

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Jersey Shop",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geistVariable = localFont({
  variable: "--font-sans",
  src: "../fonts/GeistVF.woff2",
  weight: "100 900",
  display: "swap",
  preload: true,
});

const geistMonoVariable = localFont({
  variable: "--font-geist-mono",
  src: "../fonts/GeistMonoVF.woff2",
  weight: "100 900",
  display: "swap",
  preload: true,
});

const fontSans = Onest({
  variable: "--font-sans",
  subsets: ["latin"],
})

// Viewport:
export const viewport: Viewport = {
  themeColor: "#171717",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={cn(
          `font-sans ${geistVariable.variable} ${geistMonoVariable.variable} antialiased`,
          "min-h-screen bg-background",
          "selection:bg-neutral-200 dark:selection:bg-neutral-700",
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <ToasterComponent />
        </ThemeProvider>
      </body>
    </html>
  );
}
